# Generated by Django 3.0.6 on 2020-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='name',
            field=models.CharField(default='no name', max_length=15),
        ),
    ]
